- project:
    name: openstack/mistral-specs
    templates:
      - merge-check
      - openstack-specs-jobs
    check:
      jobs:
        - openstack-tox-py27
    gate:
      jobs:
        - openstack-tox-py27
